#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#app_first_page:
#   path: /primera-pagina
#   controller: App\Controller\PageController::index
app_logout:
  path: /logout
  methods: GET